version: "3.8"
services:
  crm-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=crmDb
    ports:
      - 3307:3306
    networks:
      - uit
    volumes:
      - crmDb:/var/lib/mysql
  crm-be:
    image: tonyyou998/crm:6.6.2023.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8080:8080
    networks:
      - uit
    depends_on:
      - crm-db
volumes:
  crmDb:
networks:
  uit:
    driver: bridge

